FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

RUN bun  install

COPY . .

RUN bun run generate:db

EXPOSE 8080

CMD [ "bun","run","start:backend" ]