name: Deploy Backend to Staging
  on:
   push:
    branches: [main]

jobs:
  redeploy_Backend:
      runs_on: ubuntu-latest
      name: deploying backend to staging server

      steps:
        - run: |
              echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              mkdir -p /home/runner/.ssh
              touch /home/runner/.ssh/known_hosts
              echo "${{secrets.KNOWN_SECRETS}}" &> /home/runner/.ssh/known_hosts
              chmod 700 /home/runner/ssh_key
              ssh -i ~/ssh_key root@ip  -t "cd mono-devops/ && git pull && export PATH=/root/.nvm/versions/node/v22.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
              npm i -g bun && bun install && pm2 restart backend -server"